on: [push, pull_request]

name: Continuous integration

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.0.0  # minimum supported rust version
          - 1.10.0  # old enough
          - 1.15.0
          - 1.20.0
          - 1.25.0
          - 1.30.0
          - 1.31.0  # edition2018
          - 1.36.0
          - 1.37.0  # assert_matches! min compat version
          - stable
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args:  --all -- --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  no_std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cargo-nono
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-nono
      - name: Check no_std
        uses: actions-rs/cargo@v1
        with:
          command: nono
          args: check
